#!/usr/bin/env sh

# small power menu using rofi, i3, systemd and pm-utils
# (last 3 dependencies are adjustable below)
# tostiheld, 2016

lock_command="i3exit lock"
logout_command="i3exit logout"
suspend_command="i3exit suspend"
hibernate_command="i3exit hibernate"
reboot_command="i3exit reboot"
poweroff_command="i3exit shutdown"

# you can customise the rofi command all you want ...
rofi_command="rofi -width 20 -lines 6 -padding 5 -i -sort -p RUN"

options=$'lock\nlogout\nsuspend\nhibernate\nreboot\npoweroff'

# ... because the essential options (-dmenu and -p) are added here
eval \$"$(echo "$options" | $rofi_command -dmenu -p "")_command"
